In [1]:
import numpy as np
import pandas as pd
import glob
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.models import load_model

ModuleNotFoundError: No module named 'pandas'

In [2]:
columnNames=['Angle', ' CurrentLapTime', ' Damage', ' DistanceFromStart',' DistanceCovered', ' FuelLevel', ' Gear', ' LastLapTime',
       ' Opponent_1', 'Opponent_2', 'Opponent_3', 'Opponent_4','Opponent_5', 'Opponent_6', 'Opponent_7', 'Opponent_8',
       'Opponent_9', 'Opponent_10', 'Opponent_11', 'Opponent_12','Opponent_13', 'Opponent_14', 'Opponent_15', 'Opponent_16',
       'Opponent_17', 'Opponent_18', 'Opponent_19', 'Opponent_20','Opponent_21', 'Opponent_22', 'Opponent_23', 'Opponent_24',
       'Opponent_25', 'Opponent_26', 'Opponent_27', 'Opponent_28','Opponent_29', 'Opponent_30', 'Opponent_31', 'Opponent_32',
       'Opponent_33', 'Opponent_34', 'Opponent_35', 'Opponent_36','RacePosition', ' RPM', ' SpeedX', ' SpeedY', ' SpeedZ', ' Track_1',
       'Track_2', 'Track_3', 'Track_4', 'Track_5', 'Track_6', 'Track_7','Track_8', 'Track_9', 'Track_10', 'Track_11', 'Track_12',
       'Track_13', 'Track_14', 'Track_15', 'Track_16', 'Track_17','Track_18', 'Track_19', 'TrackPosition', ' WheelSpinVelocity_1',
        'WheelSpinVelocity_2', 'WheelSpinVelocity_3', 'WheelSpinVelocity_4','Z', ' Acceleration', 'Braking', 'Clutch', 'Gear', 'Steering']

In [3]:
path =r'E:\Academics\AIProject\Full_Data\forza' # use your path
allFiles = glob.glob(path + "\*.csv")
path2 =r'E:\Academics\AIProject\Full_Data\aalborg' # use your path
allFiles2 = glob.glob(path2+"\*.csv")
allFiles.extend(allFiles2)
training_data = pd.DataFrame(columns=columnNames)
validation_data=pd.DataFrame(columns=columnNames)
list_ = []
i=1
training_data=pd.DataFrame()
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None)
    if (i%30!=0):
        training_data=training_data.append(df)
    else:
        validation_data=validation_data.append(df)
    i+=1
training_data

Angle   CurrentLapTime   Damage   DistanceFromStart  \
0     -0.000333         -0.98200      0.0            5729.100   
1     -0.000333         -0.96200      0.0            5729.100   
2     -0.000333         -0.94200      0.0            5729.100   
3     -0.000333         -0.92200      0.0            5729.100   
4     -0.000333         -0.90200      0.0            5729.100   
5     -0.000333         -0.88200      0.0            5729.100   
6     -0.000333         -0.86200      0.0            5729.100   
7     -0.000333         -0.84200      0.0            5729.100   
8     -0.000333         -0.82200      0.0            5729.100   
9     -0.000333         -0.80200      0.0            5729.100   
10    -0.000333         -0.78200      0.0            5729.100   
11    -0.000333         -0.76200      0.0            5729.100   
12    -0.000333         -0.74200      0.0            5729.100   
13    -0.000333         -0.72200      0.0            5729.100   
14    -0.000333         -0.70200      0.0            5729.100   
15    -0.000333         -0.68200      0.0            5729.100   
16    -0.000333         -0.66200      0.0            5729.100   
17    -0.000333         -0.64200      0.0            5729.100   
18    -0.000333         -0.62200      0.0            5729.100   
19    -0.000333         -0.60200      0.0            5729.100   
20    -0.000333         -0.58200      0.0            5729.100   
21    -0.000333         -0.56200      0.0            5729.100   
22    -0.000333         -0.54200      0.0            5729.100   
23    -0.000333         -0.52200      0.0            5729.100   
24    -0.000333         -0.50200      0.0            5729.100   
25    -0.000333         -0.48200      0.0            5729.100   
26    -0.000333         -0.46200      0.0            5729.100   
27    -0.000333         -0.44200      0.0            5729.100   
28    -0.000333         -0.42200      0.0            5729.100   
29    -0.000333         -0.40200      0.0            5729.100   
...         ...              ...      ...                 ...   
12631 -0.018808          8.17001    226.0             237.834   
12632 -0.018276          8.19001    226.0             238.145   
12633 -0.017742          8.21001    226.0             238.455   
12634 -0.017203          8.23001    226.0             238.766   
12635 -0.016659          8.25001    226.0             239.077   
12636 -0.016110          8.27001    226.0             239.389   
12637 -0.015559          8.29001    226.0             239.701   
12638 -0.015007          8.31001    226.0             240.013   
12639 -0.014456          8.33001    226.0             240.325   
12640 -0.013906          8.35001    226.0             240.637   
12641 -0.013358          8.37001    226.0             240.950   
12642 -0.012810          8.39001    226.0             241.263   
12643 -0.012259          8.41001    226.0             241.576   
12644 -0.011704          8.43001    226.0             241.889   
12645 -0.011144          8.45001    226.0             242.203   
12646 -0.010581          8.47001    226.0             242.517   
12647 -0.010015          8.49001    226.0             242.831   
12648 -0.009449          8.51001    226.0             243.146   
12649 -0.008885          8.53001    226.0             243.460   
12650 -0.008323          8.55001    226.0             243.775   
12651 -0.007762          8.57001    226.0             244.090   
12652 -0.007200          8.59001    226.0             244.406   
12653 -0.006636          8.61001    226.0             244.722   
12654 -0.006069          8.63001    226.0             245.038   
12655 -0.005498          8.65001    226.0             245.354   
12656 -0.004924          8.67001    226.0             245.670   
12657 -0.004348          8.69001    226.0             245.987   
12658 -0.003772          8.71001    226.0             246.304   
12659 -0.003198          8.73001    226.0             246.621   
12660 -0.002627          8.75001    226.0    

In [4]:
del training_data['Gear']
del validation_data['Gear']
del training_data[' CurrentLapTime']
del validation_data[' CurrentLapTime']

In [5]:
X_train=training_data.loc[:,'Angle':'Z']
Y_train=training_data.loc[:,' Acceleration':'Steering']
X_val=validation_data.loc[:,'Angle':'Z']
Y_val=validation_data.loc[:,' Acceleration':'Steering']

In [6]:
print (X_train.shape)
print (Y_train.shape)
print (X_val.shape)
print (Y_val.shape)
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_val=scaler.fit_transform(X_val)
Y_train=Y_train.values
Y_val=Y_val.values
print (X_train.shape)
print (Y_train.shape)
print (X_val.shape)
print (Y_val.shape)

(820438, 73)
(820438, 4)
(27322, 73)
(27322, 4)
(820438, 73)
(820438, 4)
(27322, 73)
(27322, 4)


In [7]:
scaler.scale_

array([  1.22267255e-01,   9.40047564e+02,   1.57599893e+03,
         4.75837647e+03,   2.97571957e+00,   1.41253761e+00,
         4.39004559e+01,   7.77806087e+01,   4.54452054e+01,
         3.47894976e+01,   2.73066571e+01,   2.03542473e+01,
         2.10893599e+01,   1.79209684e+01,   1.76357096e+01,
         1.89415711e+01,   1.45532967e+01,   1.05664476e+01,
         8.79332891e+00,   1.20737683e+01,   1.50037787e+01,
         1.75214768e+01,   2.44542842e+01,   3.86273449e+01,
         5.63950763e+01,   6.10101968e+01,   4.60972601e+01,
         3.62335134e+01,   2.67309439e+01,   1.72010122e+01,
         1.67662484e+01,   1.89445111e+01,   1.92277831e+01,
         2.10297741e+01,   2.16517829e+01,   2.22520505e+01,
         2.59770563e+01,   3.08537625e+01,   3.60523081e+01,
         3.88162056e+01,   4.51539495e+01,   6.34519098e+01,
         8.33767567e+01,   9.45751199e-01,   1.51923277e+03,
         7.45233895e+01,   4.99399334e+00,   4.23157033e+00,
         2.06449224e+00,

In [8]:
learning_rate=3e-3
output_dim=Y_train.shape[1]
model=Sequential()
model.add(Dense(1024
                ,input_shape=(X_train.shape[1],),activation='relu',kernel_initializer='he_normal'))
model.add(Dense(512,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(256,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(128,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(64,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(32,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(16,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(4,kernel_initializer='he_normal'))
model.compile(optimizer=Adam(learning_rate),loss='mean_squared_error',metrics=['mae'])
model.fit(X_train,Y_train,validation_data=(X_val,Y_val),batch_size=256,epochs=500)

Train on 820438 samples, validate on 27322 samples
Epoch 1/500
820438/820438 [==============================] - 38s 46us/step - loss: 0.0153 - mean_absolute_error: 0.0580 - val_loss: 0.0112 - val_mean_absolute_error: 0.0439
Epoch 2/500
820438/820438 [==============================] - 36s 44us/step - loss: 0.0075 - mean_absolute_error: 0.0363 - val_loss: 0.0101 - val_mean_absolute_error: 0.0394
Epoch 3/500
820438/820438 [==============================] - 37s 45us/step - loss: 0.0062 - mean_absolute_error: 0.0313 - val_loss: 0.0087 - val_mean_absolute_error: 0.0369
Epoch 4/500
820438/820438 [==============================] - 37s 45us/step - loss: 0.0053 - mean_absolute_error: 0.0282 - val_loss: 0.0075 - val_mean_absolute_error: 0.0315
Epoch 5/500
820438/820438 [==============================] - 38s 46us/step - loss: 0.0047 - mean_absolute_error: 0.0259 - val_loss: 0.0075 - val_mean_absolute_error: 0.0326
Epoch 6/500
820438/820438 [==============================] - 37s 46us/step - loss: 0

Epoch 48/500
820438/820438 [==============================] - 38s 46us/step - loss: 0.0021 - mean_absolute_error: 0.0172 - val_loss: 0.0060 - val_mean_absolute_error: 0.0256
Epoch 49/500
820438/820438 [==============================] - 37s 45us/step - loss: 0.0021 - mean_absolute_error: 0.0169 - val_loss: 0.0063 - val_mean_absolute_error: 0.0264
Epoch 50/500
820438/820438 [==============================] - 38s 47us/step - loss: 0.0021 - mean_absolute_error: 0.0171 - val_loss: 0.0064 - val_mean_absolute_error: 0.0251
Epoch 51/500
103424/820438 [==>...........................] - ETA: 34s - loss: 0.0020 - mean_absolute_error: 0.0166

KeyboardInterrupt: 

In [41]:
model.predict(X_val[0].reshape(1,-1),batch_size=1)

array([[ 0.93302989,  0.02563113,  0.61886936, -0.04930833]], dtype=float32)

In [9]:
model.save(r'C:\Users\Faizan\Documents\AIProject\SavedModels\forzaborg2_256.h5')

In [2]:
model=load_model(r'C:\Users\Faizan\Documents\AIProject\SavedModels\forzamodel.h5')

In [33]:
np.array([6.72815102e-03,   0.00000000e+00,   2.98926828e+03,
         8.82075901e+03,   8.82773553e+01,   4.33248046e+00,
         6.50453941e+01,   1.33071652e+02,   1.91760555e+02,
         1.98183904e+02,   1.99349518e+02,   1.99838178e+02,
         1.99838104e+02,   1.99824619e+02,   1.99811178e+02,
         1.99743780e+02,   1.99797717e+02,   2.00000000e+02,
         2.00000000e+02,   2.00000000e+02,   2.00000000e+02,
         2.00000000e+02,   1.96869620e+02,   1.91659366e+02,
         1.61352708e+02,   1.51276094e+02,   1.79310951e+02,
         1.89481993e+02,   1.94917875e+02,   1.98549057e+02,
         1.98712633e+02,   1.98718734e+02,   1.98900035e+02,
         1.99120425e+02,   1.98792810e+02,   1.98992292e+02,
         1.98915714e+02,   1.96267422e+02,   1.95524553e+02,
         1.93991093e+02,   1.88832301e+02,   1.77603934e+02,
         9.96874482e+01,   4.84406334e+00,   8.35993868e+03,
         2.13428889e+02,   9.11619880e-01,  -5.12702917e-02,
         5.29254321e+00,   5.48623584e+00,   6.91500235e+00,
         9.19870421e+00,   1.53758853e+01,   2.00815804e+01,
         2.94262004e+01,   6.24939843e+01,   1.25257559e+02,
         1.29630135e+02,   1.28878112e+02,   7.41588063e+01,
         3.79637234e+01,   2.46591331e+01,   1.84138464e+01,
         9.90692094e+00,   7.39183783e+00,   5.86631488e+00,
         5.67355926e+00,   3.91091061e-02,   1.77636883e+02,
         1.78021565e+02,   1.82711305e+02,   1.82938183e+02,
         3.17935060e-01])

array([  6.72815102e-03,   0.00000000e+00,   2.98926828e+03,
         8.82075901e+03,   8.82773553e+01,   4.33248046e+00,
         6.50453941e+01,   1.33071652e+02,   1.91760555e+02,
         1.98183904e+02,   1.99349518e+02,   1.99838178e+02,
         1.99838104e+02,   1.99824619e+02,   1.99811178e+02,
         1.99743780e+02,   1.99797717e+02,   2.00000000e+02,
         2.00000000e+02,   2.00000000e+02,   2.00000000e+02,
         2.00000000e+02,   1.96869620e+02,   1.91659366e+02,
         1.61352708e+02,   1.51276094e+02,   1.79310951e+02,
         1.89481993e+02,   1.94917875e+02,   1.98549057e+02,
         1.98712633e+02,   1.98718734e+02,   1.98900035e+02,
         1.99120425e+02,   1.98792810e+02,   1.98992292e+02,
         1.98915714e+02,   1.96267422e+02,   1.95524553e+02,
         1.93991093e+02,   1.88832301e+02,   1.77603934e+02,
         9.96874482e+01,   4.84406334e+00,   8.35993868e+03,
         2.13428889e+02,   9.11619880e-01,  -5.12702917e-02,
         5.29254321e+00,

In [35]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 512)               37888     
_________________________________________________________________
dense_19 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_20 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_21 (Dense)             (None, 4)                 516       
Total params: 202,628
Trainable params: 202,628
Non-trainable params: 0
_________________________________________________________________
